version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - .:/code
    environment:
      - PGDATA:./storage/postgres
    ports:
      - "5432:5432"

volumes:
  storage: {}
