# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_id', models.PositiveIntegerField()),
                ('repertoire_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('group', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatTentative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_id', models.PositiveIntegerField()),
                ('repertoire_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
